server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    types { application/manifest+json webmanifest; }
    include /etc/nginx/mime.types;
    location / { try_files $uri /index.html; }
}
